export const languageItmes = [
  "Arabic عربي",
  "Chinese 中文网",
  "Indonesian INDONESIA",
  "Kyrgyz Кыргыз",
  "Persian فارسی",
  "Somali SOMALI",
  "Turkish TÜRKÇE",
  "Vietnamese TIẾNG VIỆT",
  "Azeri AZƏRBAYCAN",
  "French AFRIQUE",
  "Japanese 日本語",
  "Marathi मराठी",
  "Portuguese BRASIL",
  "Spanish MUNDO",
  "Ukrainian УКРАЇНСЬКA",
  "Bangla বাংলা",
  "Hausa HAUSA",
  "Kinyarwanda GAHUZA",
  "Nepali नेपाली",
  "Russian НА РУССКОМ",
  "Swahili SWAHILI",
  "Urdu اردو",
  "Burmese မြန်မာ",
  "Hindi हिन्दी",
  "Kirundi KIRUNDI",
  "Pashto پښتو",
  "Sinhala සිංහල",
  "Tamil தமிழ்",
  "Urdu اردو",
];
